### ISSUE TITLE
Error irrecuperable al añadir un nuevo nodo a la gobernanza

### ISSUE THREAD

**Issue by bcuestav** [opencanarias/taple-client#3]
Hola,

Gracias por haber liberado este producto que espero pueda ayudar en muchos proyectos de trazabilidad. Os comento un error que me he encontrado.

Siguiendo el tutorial descrito en la web de TAPLE y descrito como "TAPLE from 0", he producido un error irrecuperable y un aparente corte de las comunicaciones entre los nodos en caso de emplear un subject_id equivocado.

Concretamente, en el paso llamado "Adding the second node to governance", si por un error (o de forma intencionada), en los datos de la petición se utiliza un subject_id equivocado (identificador del sujeto correspondiente a la gobernanza creada en el paso justo anterior), en el nodo_0 aparece este error:

```
[2023-01-26T18:16:14Z ERROR protocol::request_manager::manager] Request Manager fail: RequestError(SubjectNotFound)
[2023-01-26T18:16:14Z INFO  rest::handlers] data: Err(InternalError { source: ComunnicationClosed })
```

Si tras el error se corrige el subject_id y se utiliza el correcto, la petición se queda bloqueada y sin respuesta, posiblemente por la pérdida de comunicaciones entre los nodos que indica el error.

La única manera de recuperarse del error que he encontrado es tirar toda la red y empezar desde cero.

El resultado esperado debería ser un error controlado indicando que no se ha encontrado el subject_id y no dejar la red en ese estado inconsistente.

Saludos cordiales!

**Comment by FlorentinPG** [comment]
Hola.

Gracias por tu aportación Benito. El error que mencionas ya lo tenemos localizado y planeamos solucionarlo con la siguiente "release" del código.

Saludos!

**Comment by FlorentinPG** [comment]
Hola,

Me complace anunciarte que el error que comentabas ya ha sido solucionado en las nuevas versiones del cliente (0.1.3 Y 0.1.4 )que se han publicado. Adicionalmente, se ha mejorado la gestión de los errores y la información que al usuario se muestra cuando estos ocurren, por lo que esperamos una mejora de la experiencia de usuario.

¡Saludos!
